
services:
  db:
    image: mysql:8.0
    container_name: db_cont  # optional, can remove to let Docker auto-name
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: notes-app:latest
    container_name: web_cont  # optional
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: notesdb
      DB_USER: notesuser
      DB_PASSWORD: notespwd
    working_dir: /app/backend
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  db_data:
